CREATE TABLE IF NOT EXISTS ACCOUNT (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(100) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATE_CREATED DATE NOT NULL,
    DATE_MODIFIED DATE DEFAULT NULL,
    DATE_DELETED DATE DEFAULT NULL,
    IS_DELETED BOOLEAN
);